### PR TITLE
Merged glossary

### PR DESCRIPTION
**Pull request by 0x70b1a5**
1. catch joe/master up to urbit/master (prep for glossary add & contributions)
2. fix all TODOs in current glossary

### CODE REVIEW

**Comment by joemfb** [comment]
Thanks, @asgardiator!

I'm not gonna merge this right now; I'm kind of in a holding pattern. @cgyarvin is editing separately, and we probably don't want to diverge too much...

Also, it looks like there's some problems on this branch; there are conflict markers committed in the glossary, some of the link changes got rolled back, etc. It'd be for the best if PRs contain only the deltas - you could get there by rebasing your branch on top of mine (or cherry-picking your commits into a new branch, if the rebase gets confused). And I don't think there's any reason to merge master back into it, we can always rebase this branch onto `urbit/docs:master`, maintaining a linear history.

I'll leave this open, we can reconcile these changes once we see what else has been done.

**Comment by 0x70b1a5** [comment]
Oops, sorry about the mix-up. Branches are such a pain. I will get this in
shape.

**Comment by joemfb** [comment]
There's a lot of dark corners in git ;)

One more thing I meant to mention; deleting the glossary and then adding a new copy with your changes removes connection across history; it'd be better to just copy your file over the existing one, and commit that (you can stage portions of the file using `git add -p`).

There's a lot going on in this branch, and rebasing could be tricky. I'd probably recommend cherry-picking individual commits.

Let me know if I can help!

**Comment by cgyarvin** [comment]
I'll be back on this in the morning.  Thanks for all the premium content, guys.

**Comment by cgyarvin** [comment]
Okay, my changes are in cgyarvin/docs.

It's interesting to speculate on a definition for the set of things that
should be in a glossary.  For instance, I took out `tape` because it
doesn't really fit under `aura`.  But as we expand this,

Also, only some kinds of atom are in here, eg, `face`.  My instinct would
be to put every kind of span and every kind of mold.  But if `tape` gets
in, there's a pretty long list of other things you'd expect to get in...

**Comment by joemfb** [comment]
Perfect, I've pulled your changes and updated urbit/docs#34.

There's a handful of other terms I'd like to get in (`alias`, `bridge`, `vase`, etc.), but those are probably best handled in separate PRs to `urbit/docs`. This has already been a pretty convoluted effort.

I do, however, have a defense of the inclusion of `tape` - at least _somewhere_. it's privileged with two (2) forms of syntax, and it's the more natural string type for programmers coming from high-level languages (like me). The distinctions between it and `@t` are obviously substantial, which is why I stuck it with `atom` ...

Anyway, I'll make those arguments in more detail separately.

**Pull request closed without merging**
